[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "electric_toolbox"
version = "0.1.0"
description = "Personal Blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.4",
    "pytailwindcss>=0.2.0",
]
